# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d352b0593e4fc8db76de54417d90cfce875204b1ac425ee46a2eb8815d7fd4f7a61ce52dddeec03f3db0da9ed3a9d32c2169267bf02e2f19591fc28a21e675c9

test:
  secret_key_base: ef9d47cb90f5e7723a6e071c70ee81c354d075c11b0c17d2a62d75abef1ebf0f91a566b8ca50502a75057fd4230a37f1b51bace2212510442233de4d30da5890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
